require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
-- require("user.comment")
-- require("user.commentary")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.tmux")
require("user.faster")
require("user.symbols-outlines")
require("user.lsp.lsp_signature")
require("user.tabnine")
require("user.fidget")
require("user.nvim_context_vt")
-- require("user.modes")
require("user.scrollbar")
-- require("user.copilot")
require("user.colorizer")
require("user.flutter")
require("user.markdown")
